#!/usr/bin/env python
import argparse
import sys
import csv

sys.path.append("./src")
import categories 
import dbmanager

class Budget:
    def __init__(self):
        #Setup Database + Categories
        self.ctgs = categories.Categories()
        self.dbman = dbmanager.DBManager()
        self.dbman.create_table("transactions", [{"name" : "Trans Date", "type" : "varchar(255)", "constraint" : ""}, 
                                                 {"name" : "Description" ,"type" : "varchar(255)", "constraint" : ""},
                                                 {"name" : "Amount"      ,"type" : "varchar(255)", "constraint" : ""}])
    
    def parse_csv(self,filename):
        data = []
        with open(filename) as csvfile:
             reader = csv.DictReader(csvfile)
             try:
                 for row in reader:
                    print(row["Trans Date"],row["Description"],row["Amount"])
                    data.append({k: v for k, v in row.items() if k=="Trans Date" or k=="Description" or k=="Amount"})
                 return data
             except E:
                 print("Parsing Error")

    def load_file(self,filename):
        data  = self.parse_csv(filename)
        print(data)
        if data:
           cdata = self.ctgs.categorize(data)
           self.dbman.load(cdata)
    
    def load_transation(self):
        pass


if __name__ == "__main__":
   b = Budget()

   #do argument parsing
   parser = argparse.ArgumentParser(description='Record and Categorize Expenses')
   parser.add_argument('action', help='show, add, delete')
   parser.add_argument('transaction', nargs='?', help='Object to add')
   parser.add_argument('--f')
   args = parser.parse_args()

   if   args.action == 'show':
       pass
   elif args.action == 'add':
       if args.f:
           b.load_file(args.f)
   elif args.action == 'delete':
       pass
   else:
       print("Incorrect usage")
